# Generated by Django 4.0.4 on 2022-05-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
